[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[build]
target = "riscv32imac-unknown-none-elf"

[env]
ESP_LOG_LEVEL = "INFO"

[unstable]
build-std = ["core", "alloc"]
